# Generated by Django 6.0.1 on 2026-01-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('bus_type', models.CharField(choices=[('EKONOMI', 'Ekonomi'), ('EXEC', 'Executive'), ('SLEEPER', 'Sleeper')], max_length=20)),
                ('route_from', models.CharField(max_length=80)),
                ('route_to', models.CharField(max_length=80)),
                ('depart_at', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('capacity_total', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=12)),
                ('hold_token', models.CharField(blank=True, max_length=64, null=True)),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_wa', models.CharField(blank=True, max_length=30, null=True)),
                ('claim_code', models.CharField(blank=True, max_length=20, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'status'], name='booking_sea_trip_id_e455cd_idx'), models.Index(fields=['status', 'hold_until'], name='booking_sea_status_266a47_idx'), models.Index(fields=['claim_code'], name='booking_sea_claim_c_ddfcad_idx')],
                'unique_together': {('trip', 'code')},
            },
        ),
    ]
