# Generated by Django 6.0.1 on 2026-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booking_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='admin_wa',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['booking_code'], name='booking_sea_booking_a2ace4_idx'),
        ),
    ]
